version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - .:/app:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    volumes:
      - ./:/app:delegated
      - composer:/home/app/.composer
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
        PHP_VERSION: ${PHP_VERSION}
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
      ADMINER_PLUGINS: 'edit-foreign email-table wymeditor'
    links:
      - db
    ports:
      - 8888:8080


volumes:
  mysql:
  composer:
